### ISSUE TITLE
facts2ca.pp puppet4.0 parsing issue

### ISSUE THREAD

**Issue by DoctahPopp871** [cloudaware/public-modules#1]
mode    => 0640

This cannot be a fixed num in puppet 4.0 this needs to be in single quotes in order to be parsed correctly. Issue on lines 24,33, and 43. Need to be wrapped in single quotes to work in Puppet4.0

mode    => '0640'

Relevant error:
Error: Failed to apply catalog: Parameter mode failed on File[facts2ca::config]: The file mode specification must be a string, not 'Fixnum' at /etc/puppetlabs/code/environments/testing/modules/cloudaware/manifests/facts2ca.pp:20

**Comment by DoctahPopp871** [comment]
Found two additional issues with running this on PE 2015.3 Puppet 4.0 

Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/mcollective/facts2ca.yaml20160122-26164-3cr33d.lock at 20:/etc/puppetlabs/code/environments/testing/modules/cloudaware/manifests/facts2ca.pp

The mcollective dir is actually /etc/puppetlabs/mcollective in PE2015.3

Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /usr/share/mcollective/plugins/mcollective/application/facts2ca.rb20160122-26164-t7n5dm.lock at 29:/etc/puppetlabs/code/environments/testing/modules/cloudaware/manifests/facts2ca.pp

This path is actually /opt/puppetlabs/mcollective in PE2015.3

**Comment by szhuga** [comment]
Thank you for reporting this issue. Puppet 4.x support was added in f55ab2e3d1042fb9469e14f1223f72acf4be3560.
