### ISSUE TITLE
Facter::Util::EC2 deprecated. 

### ISSUE THREAD

**Issue by DoctahPopp871** [cloudaware/public-modules#2]
https://github.com/cloudaware/public-modules/blob/master/cloudaware/lib/facter/ec2.rb

There is a require statement for 'facter/util/ec2'  this .rb file was part of facter 2.2 but is no longer part of the util directory in the latest version of puppet 4.0 and facter3.1 . Please include the EC2.rb file https://docs.omniref.com/ruby/gems/facter/2.2.0/symbols/Facter::Util::EC2 in the lib/facter/util directory in your module.  The below errors are produced without this .rb which I have manually added to my deployment :

Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/ec2.rb: cannot load such file -- facter/util/ec2

**Comment by szhuga** [comment]
Thank you for reporting this issue. Facter 3.x support was added in f55ab2e3d1042fb9469e14f1223f72acf4be3560.
